steps: 

#Execute SAST Scan using SonarCloud in GCP DevSecOps Pipeline
  - name: maven:3-openjdk-18-slim
    entrypoint: mvn
    args: ['verify', 'sonar:sonar','-Dsonar.host.url=https://sonarcloud.io','-Dsonar.organization=gcpcodescan123','-Dsonar.projectKey=gcpsonar','-Dsonar.token=${_SONAR_TOKEN}']
    id: SAST Scan using SonarCloud in GCP DevSecOps Pipeline

#Run Software Composition Analysis (SCA security scan) using Snyk in GCP DevSecOps Pipeline
options:
  logging: CLOUD_LOGGING_ONLY